Changes for the merge operations
hpc-io/vol-async pull request #26
Opened 2022-08-10 21:42 UTC by kamalchowdhurylbl

2022-08-10 22:33 UTC, kamalchowdhurylbl commented
changes in the vol_async file

2022-08-12 17:31 UTC, houjun commented on src/h5_async_vol.c
> +Asynchronous I/O VOL kamal Connector (AsyncVOL) Copyright (c) 2021, The
reverse this change / remove your name

2022-08-12 17:31 UTC, houjun commented on src/h5_async_vol.c
> +#define PRINT_ERROR_STACK 1
reverse this change

2022-08-12 17:31 UTC, houjun commented on src/h5_async_vol.c
> -    bool          disable_async_dset_get; /* Disable async execution for dataset get */
add disable_async_dset_get line back

2022-08-12 17:31 UTC, houjun commented on src/h5_async_vol.c
> +
remove empty line

2022-08-12 17:31 UTC, houjun commented on src/h5_async_vol.c
> +
remove empty line

2022-08-12 17:31 UTC, houjun commented on src/h5_async_vol.c
> -    aid->disable_async_dset_get = true;
add disable_async_dset_get line back

2022-08-12 17:31 UTC, houjun commented on src/h5_async_vol.c
> -
add lines 1324-27 back

2022-08-12 17:31 UTC, houjun commented on src/h5_async_vol.c
> +    // fprintf(stderr,"task is_merge=%d\n",task->is_merge);
remove commented cout line

2022-08-12 17:31 UTC, houjun commented on src/h5_async_vol.c
> +    // fprintf(stderr," args  mem_type_id=%llu\n",args->mem_type_id);
remove commented cout line

2022-08-12 17:31 UTC, houjun commented on src/h5_async_vol.c
> +    //  H5Tclose(args->mem_type_id);
revert / uncomment 69 and 70

2022-08-12 17:31 UTC, houjun commented on src/h5_async_vol.c
> +    int                         N1 = 20;
remove unused variables

2022-08-12 17:31 UTC, houjun commented on src/h5_async_vol.c
> +                    iter_file_count = malloc(ndim * sizeof(hsize_t));
move all the malloc outside the DL_FOREACH loop, so they are only allocated and freed once

2022-08-12 17:31 UTC, houjun commented on src/h5_async_vol.c
> +                    free(iter_file_count);
move all the free outside the DL_FOREACH loop, to match the malloc

2022-08-12 17:31 UTC, houjun commented on src/h5_async_vol.c
> +    // return  return_val;
remove commented out codes

2022-08-12 17:31 UTC, houjun commented on src/h5_async_vol.c
> +    // fprintf(stderr,"mem_type_id=%llu\n",mem_type_id);
remove commented out line

2022-08-12 17:31 UTC, houjun commented on src/h5_async_vol.c
> +    if (req) {
reverse the changes / add back original code

2022-08-12 17:31 UTC, houjun commented on src/h5_async_vol.c
> +    under_vol_info_end   = strrchr(str, '}');
reverse the changes / add back original code

2022-08-12 17:31 UTC, houjun commented on test/1d_asyn_MPI_write.c
> +            */
Are these commented out code useful? If not, remove them.

2022-08-12 17:31 UTC, houjun commented on test/1d_asyn_MPI_write.c
> +        data_transfer_propertylist, data,es_id);
Are these commented out code useful? If not, remove them.

2022-08-12 17:31 UTC, houjun commented on test/2d_asyn_MPI_write.c
> +   }; */
These should be uncommented and used for running this test.

2022-08-12 17:31 UTC, houjun commented on test/2d_asyn_MPI_write.c
> +        data,es_id);
Are these commented out code useful? If not, remove them.

2022-08-12 17:31 UTC, houjun commented on test/3d_asyn_MPI_write.c
> +     };  */
Are these commented out code useful? If not, remove them.

2022-08-12 17:31 UTC, houjun commented on test/3d_asyn_MPI_write.c
> +                    } */
Are these commented out code useful? If not, remove them.

2022-08-12 17:31 UTC, houjun commented on test/Makefile
> +    3d_asyn_MPI_write.c 1d_async_write_performance
1d_async_write_performance -> 1d_async_write_performance.c

2022-08-12 17:31 UTC, houjun commented on src/h5_async_vol.c
> +        goto done;
add #ifdef ENABLE_WRITE_MERGE ... #endif before 9973 and after 9977, so that the merge only happens when enabled at compile time

2022-08-12 17:32 UTC, houjun commented on src/h5_async_vol.c
> +Asynchronous I/O VOL  Connector (AsyncVOL) Copyright (c) 2021, The
remove the extra space

2022-08-12 17:32 UTC, houjun commented on src/h5_async_vol.c
> + #define PRINT_ERROR_STACK           1
revert to commented line

2022-08-25 21:01 UTC, houjun commented on src/Makefile
> +CFLAGS = $(DEBUG) -fPIC -I$(ABT_DIR)/include -I$(HDF5_DIR)/include -Wall -DENABLE_WRITE_MERGE
remove "-DENABLE_WRITE_MERGE", it should not be enabled by default

2022-08-29 22:19 UTC, houjun requested changes
@kamalchowdhurylbl Please rerun the clang-format tool with "clang-format -i -style=file ./*.c", there are too many formatting changes with your latest commit.

2022-08-29 22:19 UTC, houjun commented on src/Makefile
> +CFLAGS = $(DEBUG) -fPIC -I$(ABT_DIR)/include -I$(HDF5_DIR)/include -Wall -DENABLE_WRITE_MERGE
-DENABLE_WRITE_MERGE should be removed/commented out to not turn on the merge feature by default, until we do more testing

2022-08-29 22:19 UTC, houjun commented on src/h5_async_vol.c
> +    void                *under_wrap_ctx; /* Object wrapping context for under VOL */
You need to use the https://github.com/hpc-io/vol-async/blob/develop/.clang-format file when you run clang-format command, e.g. under vol-async/src do "clang-format -i -style=file ./*.c"

2024-05-31 14:58 UTC, brtnfld commented
@houjun , do you know the status of this PR? Was it just a matter of format changes? Should we sync it with develop and format it?

2024-05-31 16:29 UTC, houjun commented
@brtnfld, this is not ready to merge yet, I'll change it to a draft.

2025-04-28 23:28 UTC, closed without merging